# ===============================
# = SERVER CONFIG
# ===============================
server.port=8080

# ===============================
# = EMAIL CONFIGURATION
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=balurajupv@gmail.com
spring.mail.password=tmcwtxvecwgmzeom
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App email verification base URL

#app.activation.base-url=http://localhost:8080/api/users/activate/

app.activation.base-url=http://192.168.29.19:8080/api/users/activate


app.activation.expiry-minutes=15

# ===============================
# = DATABASE CONFIG (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/walletdb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# = HIBERNATE / JPA
# ===============================
# IMPORTANT: First run with create to auto generate tables
spring.jpa.hibernate.ddl-auto=update

# After tables are created, change to: update
# spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect

# ===============================
# = LOGGING 
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


whatsapp.token=EAAOEvqSaCuIBRWysXRuPKEq9pLTH47C8J9AZA8t4CIJjAZAk5WDuVPcvcjTvnlXY4CCRC4jFbYO5NI1OV8LZBGXD6njxrrNEpn9GuMj0pVba9Y7E37JpxCZB9ZCeo8SChSaN03lU2hi8GLVrwU8ZCVXxl7yirnE4bQpZAnVN9xXs9zpAQ1d2dxjIbSvBFcCgeG3AaVLG73v2ZBHy7qckU5odjdUdF3xkZCVCxp60XGzfCSPnzNMd2QqQqgrNC9CSSOZCprNIIPXsZCZBgINbc1zj95P31iYZD
whatsapp.phoneNumberId=1071199822743401
